trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: sbt
    dockerfile: '$(Build.SourcesDirectory)/debian/Dockerfile'
    containerRegistry: 'cr-connection'
    tags: |
      1.3.3_$(Build.BuildId)             

