trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'cr-connection'
    repository: 'sbt'
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/debian/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/debian'
    tags: |
      $(Build.BuildId)
      latest
    arguments: '--build-arg BASE_IMAGE_TAG=openjdk:11-jdk-stretch'

- task: Docker@2
  inputs:
    containerRegistry: 'cr-connection'
    repository: 'sbt'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest

